package com.example.senon.nancyclass.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.senon.nancyclass.greendaoentity.UserDetails;
import com.example.senon.nancyclass.greendaoentity.UserReview;

import com.example.senon.nancyclass.greendao.UserDetailsDao;
import com.example.senon.nancyclass.greendao.UserReviewDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDetailsDaoConfig;
    private final DaoConfig userReviewDaoConfig;

    private final UserDetailsDao userDetailsDao;
    private final UserReviewDao userReviewDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDetailsDaoConfig = daoConfigMap.get(UserDetailsDao.class).clone();
        userDetailsDaoConfig.initIdentityScope(type);

        userReviewDaoConfig = daoConfigMap.get(UserReviewDao.class).clone();
        userReviewDaoConfig.initIdentityScope(type);

        userDetailsDao = new UserDetailsDao(userDetailsDaoConfig, this);
        userReviewDao = new UserReviewDao(userReviewDaoConfig, this);

        registerDao(UserDetails.class, userDetailsDao);
        registerDao(UserReview.class, userReviewDao);
    }
    
    public void clear() {
        userDetailsDaoConfig.clearIdentityScope();
        userReviewDaoConfig.clearIdentityScope();
    }

    public UserDetailsDao getUserDetailsDao() {
        return userDetailsDao;
    }

    public UserReviewDao getUserReviewDao() {
        return userReviewDao;
    }

}
